server:
  port: ${SERVER_PORT:8888}
spring:
  application:
    name: ${APPLICATION_NAME:spring-gateway}
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    default-property-inclusion: non_null
    serialization:
      indent_output: true
  cloud:
    nacos:
      discovery:
        service: ${APPLICATION_SERVICE_NAME:${APPLICATION_NAME:spring-gateway}}
        server-addr: ${NACOS_ADDR:${REGISTRY_INTERNAL_HOST}:${REGISTRY_INTERNAL_HTTP_PORT}}
        username: ${NACOS_USERNAME:${REGISTRY_USERNAME:nacos}}
        password: ${NACOS_PASSWORD:${REGISTRY_PASSWORD:nacos}}
        namespace: ${NACOS_NAMESPACE:${REGISTRY_NAMESPACE:public}}
    loadbalancer:
      ribbon:
        enabled: true
zuul:
  routes:
    service-consumer:
      path: /service-consumer/**
      service-id: service-consumer
      strip-prefix: true
    service-provider:
      path: /service-provider/**
      service-id: service-provider
      strip-prefix: true
    service-provider-reactive:
      path: /service-provider-reactive/**
      service-id: service-provider-reactive
      strip-prefix: true
    http:
      url: http://demo.live.local:11813/
      path: /http/**
      strip-prefix: true
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: ${LIVE_LOG_LEVEL:INFO}
    reactor:
      netty: ${LIVE_LOG_LEVEL:INFO}
    root: ${LIVE_LOG_LEVEL:INFO}
