spring:
  application:
    name: sofarpc-consumer
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    default-property-inclusion: non_null
    serialization:
      indent_output: true

com:
  alipay:
    sofa:
      rpc:
        registry-address: nacos://${NACOS_ADDR:${REGISTRY_INTERNAL_HOST}:${REGISTRY_INTERNAL_HTTP_PORT}}?username=${NACOS_USERNAME:${REGISTRY_USERNAME:nacos}}&password=${NACOS_PASSWORD:${REGISTRY_PASSWORD:nacos}}&namespace=${NACOS_NAMESPACE}
logging:
  level:
    com.alipay.sofa.rpc: INFO