spring:
  application:
    name: ${APPLICATION_NAME:sofarpc-consumer}
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    default-property-inclusion: non_null
    serialization:
      indent_output: true
  cloud:
    nacos:
      discovery:
        enabled: ${NACOS_ENABLED:true}
        service: ${APPLICATION_SERVICE_NAME:${APPLICATION_NAME:sofarpc-consumer}}
        namespace: ${NACOS_NAMESPACE:${REGISTRY_NAMESPACE:public}}
        password: ${NACOS_PASSWORD:${REGISTRY_PASSWORD:nacos}}
        server-addr: ${NACOS_ADDR:${REGISTRY_INTERNAL_HOST}:${REGISTRY_INTERNAL_HTTP_PORT}}
        username: ${NACOS_USERNAME:${REGISTRY_USERNAME:nacos}}
      password: ${NACOS_PASSWORD:${REGISTRY_PASSWORD:nacos}}
      username: ${NACOS_USERNAME:${REGISTRY_USERNAME:nacos}}
server:
  port: ${SERVER_PORT:${random.int[10000,10999]}}

com:
  alipay:
    sofa:
      rpc:
        registry-address: nacos://${NACOS_ADDR:${REGISTRY_INTERNAL_HOST}:${REGISTRY_INTERNAL_HTTP_PORT}}?username=${NACOS_USERNAME:${REGISTRY_USERNAME:nacos}}&password=${NACOS_PASSWORD:${REGISTRY_PASSWORD:nacos}}&namespace=${NACOS_NAMESPACE}

logging:
  level:
    com.alipay.sofa.rpc: INFO
debug: true