spring:
  application:
    name: sofarpc-provider
com:
  alipay:
    sofa:
      rpc:
        registry-address: nacos://${NACOS_ADDR:${REGISTRY_INTERNAL_HOST}:${REGISTRY_INTERNAL_HTTP_PORT}}?username=${NACOS_USERNAME:${REGISTRY_USERNAME:nacos}}&password=${NACOS_PASSWORD:${REGISTRY_PASSWORD:nacos}}&namespace=${NACOS_NAMESPACE}
        bind-network-interface: en0
logging:
  level:
    com.alipay.sofa.rpc: INFO

echo:
  sleepTime: ${RESPONSE_WAIT_TIME:2000}
  randomTime: ${RESPONSE_RANDOM_TIME:1000}
  suffix:
mock:
  cpuPercent: ${CPU_PERCENT:0.2}