server:
  port: ${SERVER_PORT:8888}
management:
  endpoint:
    gateway:
      access: read_only
  endpoints:
    web:
      exposure:
        include: "gateway"
spring:
  application:
    name: ${APPLICATION_NAME:spring-gateway}
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    default-property-inclusion: non_null
    serialization:
      indent_output: true
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: rocketmq
              uri: lb://service-rocketmq
              predicates:
                - Path=/service-rocketmq/**
                - Method=GET
              filters:
                - StripPrefix=1
            - id: order
              uri: lb://service-order
              predicates:
                - Path=/service-order/**
              filters:
                - StripPrefix=1
            - id: consumer
              uri: lb://service-consumer
              predicates:
                - Path=/service-consumer/**
                - Method=GET
              filters:
                - StripPrefix=1
            - id: provider-reactive
              uri: lb://service-provider-reactive
              predicates:
                - Path=/service-provider-reactive/**
                - Method=GET
              filters:
                - StripPrefix=1
                - Retry=5
            - id: provider
              uri: lb://service-provider
              predicates:
                - Path=/service-provider/**
                - Method=GET
              filters:
                - StripPrefix=1
                - Retry=5
            - id: dubbo3-consumer
              uri: lb://dubbo3-consumer
              predicates:
                - Path=/dubbo3-consumer/**
                - Method=GET
              filters:
                - StripPrefix=1
            - id: dubbo2-consumer
              uri: lb://dubbo2-consumer
              predicates:
                - Path=/dubbo2-consumer/**
                - Method=GET
              filters:
                - StripPrefix=1
            - id: sofarpc-consumer
              uri: lb://sofarpc-consumer
              predicates:
                - Path=/sofarpc-consumer/**
                - Method=GET
              filters:
                - StripPrefix=1
    nacos:
      discovery:
        service: ${APPLICATION_SERVICE_NAME:${APPLICATION_NAME:spring-gateway}}
        server-addr: ${NACOS_ADDR:${REGISTRY_INTERNAL_HOST}:${REGISTRY_INTERNAL_HTTP_PORT}}
        username: ${NACOS_USERNAME:${REGISTRY_USERNAME:nacos}}
        password: ${NACOS_PASSWORD:${REGISTRY_PASSWORD:nacos}}
        namespace: ${NACOS_NAMESPACE:${REGISTRY_NAMESPACE:public}}
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: ${LIVE_LOG_LEVEL:INFO}
    reactor:
      netty: ${LIVE_LOG_LEVEL:INFO}
    root: ${LIVE_LOG_LEVEL:INFO}
