spring:
  application:
    name: service-order
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    default-property-inclusion: non_null
    serialization:
      indent_output: true
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:${REGISTRY_INTERNAL_HOST}:${REGISTRY_INTERNAL_HTTP_PORT}}
        fail-fast: true
        namespace: ${NACOS_NAMESPACE:public}
        username: ${NACOS_USERNAME:${REGISTRY_USERNAME:nacos}}
        password: ${NACOS_PASSWORD:${REGISTRY_PASSWORD:nacos}}
      username: ${NACOS_USERNAME:${REGISTRY_USERNAME:nacos}}
      password: ${NACOS_PASSWORD:${REGISTRY_PASSWORD:nacos}}
  cache:
    type: ${CACHE_TYPE:CAFFEINE}
    redis:
      host: ${REDIS_ADDR}
      port: 6379
  datasource:
    url: jdbc:mariadb://${DB_ADDR}/live_demo
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
server:
  port: ${SERVER_PORT:${random.int[12000,12999]}}
