spring:
  application:
    name: ${APPLICATION_NAME:grpc-provider}
  cloud:
    nacos:
      discovery:
        service: ${APPLICATION_SERVICE_NAME:${APPLICATION_NAME:grpc-provider}}
        server-addr: ${NACOS_ADDR:${REGISTRY_INTERNAL_HOST}:${REGISTRY_INTERNAL_HTTP_PORT}}
        namespace: ${NACOS_NAMESPACE:${REGISTRY_NAMESPACE:public}}
        username: ${NACOS_USERNAME:${REGISTRY_USERNAME:nacos}}
        password: ${NACOS_PASSWORD:${REGISTRY_PASSWORD:nacos}}
grpc:
  server:
    port: ${GRPC_SERVER_PORT:${random.int[20000,21000]}}
server:
  port: ${SERVER_PORT:${random.int[20000,21000]}}
