spring:
  application:
    name: grpc-consumer
  cloud:
    nacos:
      discovery:
        heart-beat:
          enabled: true
        heart-beat-interval: 5000
        server-addr: ${NACOS_ADDR:${REGISTRY_INTERNAL_HOST}:${REGISTRY_INTERNAL_HTTP_PORT}}
        namespace: ${NACOS_NAMESPACE:public}
        username: ${NACOS_USERNAME:${REGISTRY_USERNAME:nacos}}
        password: ${NACOS_PASSWORD:${REGISTRY_PASSWORD:nacos}}
grpc:
  client:
    grpc-provider:
      address: 'discovery:///grpc-provider'
      #static address
      #address: 'static://127.0.0.1:9898'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

server:
  port: ${SERVER_PORT:8080} # Web Server