spring:
  application:
    name: service-product
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    default-property-inclusion: non_null
    serialization:
      indent_output: true
  cloud:
    nacos:
      discovery:
        service: ${APPLICATION_SERVICE_NAME:${APPLICATION_NAME:service-product}}
        server-addr: ${NACOS_ADDR:${REGISTRY_INTERNAL_HOST}:${REGISTRY_INTERNAL_HTTP_PORT}}
        fail-fast: true
        namespace: ${NACOS_NAMESPACE:${REGISTRY_NAMESPACE:public}}
        username: ${NACOS_USERNAME:${REGISTRY_USERNAME:nacos}}
        password: ${NACOS_PASSWORD:${REGISTRY_PASSWORD:nacos}}
      username: ${NACOS_USERNAME:${REGISTRY_USERNAME:nacos}}
      password: ${NACOS_PASSWORD:${REGISTRY_PASSWORD:nacos}}
  data:
    mongodb:
      uri: mongodb://${DB_USER}:${DB_PASSWORD}@${DB_ADDR}/live_demo
server:
  port: ${SERVER_PORT:${random.int[12000,12999]}}
